### ISSUE TITLE
Kibana not accessible on port 64297

### ISSUE THREAD

**Issue by MadGeckoo** [dtag-dev-sec/tpotce#362]
Hi, I got the same exact problem as #335 . On 03.05.2019, I installed latest version of T-pot using installer on clean cloud Debian.

I can access cockpit and also tcpdump shows incoming and outgoing packets when I connect to 64297, but I can't seem to get Kibana UI.

Outputs of netstat and dps.sh are the same as in #335 . Nginx access.log and error.log in container are empty.

My setup is cloud machine in openstack. TLS 1.3 is supported by all my browsers

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

[debian@cajnik:~]$ uname -a
Linux cajnik 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
[debian@cajnik:~]$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

- What T-Pot version are you currently using?
19.03

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Nextgen

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
cloud

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
there was the same issue during install as in
https://github.com/dtag-dev-sec/tpotce/issues/346#issuecomment-482097528

- How long has your installation been running?

standard duration, I believe

- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.

![image](https://user-images.githubusercontent.com/3979652/57221517-db69d300-6fff-11e9-9bb4-bf466b08a046.png)

![image](https://user-images.githubusercontent.com/3979652/57221552-f9373800-6fff-11e9-9e10-32899bfe286a.png)

- How much free disk space is available (`df -h`)?
144GB
- What is the current container status (`dps.sh`)?

![image](https://user-images.githubusercontent.com/3979652/57221602-271c7c80-7000-11e9-9951-68ae4ad9a209.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
Tpot stopped, netstat -tulpen output:
![image](https://user-images.githubusercontent.com/3979652/57222036-8202a380-7001-11e9-8a84-4c9ad740a480.png)

Tpot running, netstat -tulpen output, grep 64297:

![image](https://user-images.githubusercontent.com/3979652/57222205-0c4b0780-7002-11e9-8ba4-1ecaba98bcce.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
1. Can you access honeypot services, i.e. Cowrie on tcp/22 or Snare on tcp/80?
2. Access to Kibana is only supported through `https://<your_host>:64297`

**Comment by MadGeckoo** [comment]
1. I can access Cowrie, Snare, even Cockpit.
2. I am accesing through that.
3. 
![image](https://user-images.githubusercontent.com/3979652/57313650-54485800-70f0-11e9-9d00-75d33f8296ca.png)
 
![image](https://user-images.githubusercontent.com/3979652/57313714-72ae5380-70f0-11e9-9058-b2bf5a7c20d0.png)



4. I reinstalled as sudo su -, I even got glimpse of succesfull connection (got the warning about bad certificate), but after kibana container started, situation was the same again and now I can't connect to it.

**Comment by t3chn0m4g3** [comment]
If you are tunneling please rule out that the docker interfaces do not overlap with your local subset. If they do you will be unable to connect.
Everything else looks perfectly fine.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.

**Comment by MadGeckoo** [comment]
Tunneling is indeed the problem. How can I modify containers (?) to use different IPs for br- interfaces?

**Comment by t3chn0m4g3** [comment]
#345

**Comment by MadGeckoo** [comment]
I've tried to set IP for bridge interfaces in /etc/docker/daemon.json. Interfaces br-xxxxxx which had IPs from the same range as eth0 got new addresses. But it didn't solve the problem.

Since I see packets arriving at port 64297 with tcpdump, I assume, there isn't problem getting to the machine from outside. I can still connect to cockpit without issue.

I can also do curl on the machine and get correct page
![docker_problem](https://user-images.githubusercontent.com/3979652/57871747-56a26480-780a-11e9-9ede-baa4644ecbdb.png)

Suricata also sees me, but here's the problem, When I am connecting to the cockpit, suricata sees TLS correct version:
![docker_problem_2](https://user-images.githubusercontent.com/3979652/57871746-56a26480-780a-11e9-8f9d-e04a66ff0c65.png)

When I am connecting to the 64297, TLS negotiating doesnt even go properly.
![docker_problem_3](https://user-images.githubusercontent.com/3979652/57871744-56a26480-780a-11e9-94bd-f167870cec40.png)

Since nginx handles cockpit and kibana, and cockpit works properly, there shouldn't be an issue in nginx. 

So I guess problem is somewhere in docker networking and related iptables...which is weird, since the last version 1811 worked for me in the same environment out of box. 

Any ideas?

**Comment by t3chn0m4g3** [comment]
Can you install from scratch today. Debian docker received a patch yesterday moving away from iptables-legacy to uptakes again. Maybe this can solve things for you. Other than that I have no more ideas since tunneling works fine in my end as well.

**Comment by MadGeckoo** [comment]
Finished installation few minutes ago. Nothing has changed. From netstat it seems that ssh is set up the same way as I suppose nginx reverse proxy is on the side of host system
![image](https://user-images.githubusercontent.com/3979652/57886244-0d174100-782d-11e9-80ec-a6e01a18a129.png)
and also, its weird that dps.sh doesnt show 0.0.0.0:64297->64297, even tho netstat shows it....also, no rules with ports 64297,64294 or 64295 in iptables

**Comment by t3chn0m4g3** [comment]
That is normal, since the NGINX container uses the hosts network stack as do glutton, dionaea, p0f, suricata or honeytrap.
However this rules out the assumption that iptables is the culprit.

**Comment by MadGeckoo** [comment]
So, I digged in some more...it seems, that somehow Nginx is the problem

First picture is curl from the tpot machine itself

![image](https://user-images.githubusercontent.com/3979652/60182675-08c74600-9825-11e9-8f64-eef0ff3ceee9.png)

Second picture - I tried to connect from the machine in the same subnet and it shuts down after first Client Hello

![image](https://user-images.githubusercontent.com/3979652/60182777-3f9d5c00-9825-11e9-91d6-12231c241245.png)

I changed nginx container from read-only to writable, but I am not sure, what might be the problem.

**Comment by t3chn0m4g3** [comment]
We are forcing TLS 1.3 which some browsers are having problems with.

**Comment by MadGeckoo** [comment]
Did you make big changes in how docker networking is built between 1811 and 1903 version?

**Comment by t3chn0m4g3** [comment]
Yes, we switched from Ubuntu to Debian. While Ubuntu uses netplan Debian uses ifupdown.

**Comment by MadGeckoo** [comment]
I wanted to install older versions based on ubuntu, but they don't work. Can you maybe provide me with 18.10 working version - just so I can debug this, please? I have a hunch it's caused by different cloud-init configuration for debian in cloud I am using.

**Comment by t3chn0m4g3** [comment]
Unfortunately this is not possible due to the evergreening nature of the t-pot project. Only 19.03 is possible.
