### ISSUE TITLE
ELK 7.x shared failed (even after fix from post)

### ISSUE THREAD

**Issue by Patrik-Hansson** [dtag-dev-sec/tpotce#539]
Creating a new issue so i don't spam the ELK 7.0 rollout post.

After running the ELK 7.x in nextgen without issues for some time i today got the shards failed error when trying to view the T-Pot dashboard. 
Running the fix in the dev console gives me the "acknowledge true" response.
Found this https://github.com/zammad/zammad/issues/2821#issuecomment-558071394 that may indicate that a setting in elasticsearch.yml needs to be added ?

Settings:

> "logstash-2020.02.10" : {
    "settings" : {
      "index" : {
        "mapping" : {
          "total_fields" : {
            "limit" : "2000"
          }
        },
        "refresh_interval" : "5s",
        "number_of_shards" : "1",
        "provided_name" : "logstash-2020.02.10",
        "query" : {
          "default_field" : "fields.*"
        },
        "creation_date" : "1581292800928",
        "number_of_replicas" : "0",
        "uuid" : "d1PTu_aURreGEF3bz2XEFw",
        "version" : {
          "created" : "7050299"
        }
      }
    }

Error:
{
  "took": 150,
  "timed_out": false,
  "_shards": {
    "total": 31,
    "successful": 30,
    "skipped": 0,
    "failed": 1,
    "failures": [
      {
        "shard": 0,
        "index": "logstash-2020.02.10",
        "node": "uNstleigT_a9BZgqS3jRYA",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"query_string\" : {\n          \"query\" : \"type:\\\"Adbhoney\\\" OR type:\\\"Ciscoasa\\\" OR type:\\\"CitrixHoneypot\\\" OR type:\\\"ConPot\\\" OR type:\\\"Cowrie\\\" OR type:\\\"Dionaea\\\" OR type:\\\"ElasticPot\\\" OR type:\\\"Glastopf\\\" OR type:\\\"Glutton\\\" OR type:\\\"Heralding\\\" OR type:\\\"Honeypy\\\" OR type:\\\"Honeytrap\\\" OR type:\\\"Mailoney\\\" OR type:\\\"Medpot\\\" OR type:\\\"Rdpy\\\" OR type:\\\"Tanner\\\"\",\n          \"fields\" : [ ],\n          \"type\" : \"best_fields\",\n          \"default_operator\" : \"or\",\n          \"max_determinized_states\" : 10000,\n          \"enable_position_increments\" : true,\n          \"fuzziness\" : \"AUTO\",\n          \"fuzzy_prefix_length\" : 0,\n          \"fuzzy_max_expansions\" : 50,\n          \"phrase_slop\" : 0,\n          \"analyze_wildcard\" : true,\n          \"time_zone\" : \"Europe/Stockholm\",\n          \"escape\" : false,\n          \"auto_generate_synonyms_phrase_query\" : true,\n          \"fuzzy_transpositions\" : true,\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"query_string\" : {\n          \"query\" : \"*\",\n          \"default_field\" : \"*\",\n          \"fields\" : [ ],\n          \"type\" : \"best_fields\",\n          \"default_operator\" : \"or\",\n          \"max_determinized_states\" : 10000,\n          \"enable_position_increments\" : true,\n          \"fuzziness\" : \"AUTO\",\n          \"fuzzy_prefix_length\" : 0,\n          \"fuzzy_max_expansions\" : 50,\n          \"phrase_slop\" : 0,\n          \"analyze_wildcard\" : true,\n          \"time_zone\" : \"Europe/Stockholm\",\n          \"escape\" : false,\n          \"auto_generate_synonyms_phrase_query\" : true,\n          \"fuzzy_transpositions\" : true,\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"filter\" : [\n      {\n        \"match_all\" : {\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"range\" : {\n          \"@timestamp\" : {\n            \"from\" : \"2020-02-10T07:30:20.354Z\",\n            \"to\" : \"2020-02-10T07:45:20.354Z\",\n            \"include_lower\" : true,\n            \"include_upper\" : true,\n            \"format\" : \"strict_date_optional_time\",\n            \"boost\" : 1.0\n          }\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}",
          "index_uuid": "d1PTu_aURreGEF3bz2XEFw",
          "index": "logstash-2020.02.10",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "field expansion matches too many fields, limit: 1024, got: 1122"
          }
        }
      }
    ]
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  },
  "aggregations": {
    "2": {
      "buckets": []
    }
  }
}

**Comment by t3chn0m4g3** [comment]
I am not so sure about [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-settings.html). The shard exception is an index based error, that should be fixed with `"default_field" : "fields.*"`. Setting this on the node level seems redundant / odd to me.
So far I could not reproduce the error on my installations, but will keep this open just in case.

**Comment by Patrik-Hansson** [comment]
This fixed it:
Copy elasticsearch.yml from elasticsearch container to /data/elk/config/elasticsearch.yml
add indices.query.bool.max_clause_count: 2000 to the file.
add a volume to map the config file in /opt/tpot/etc/tpot.yml
restart tpot.service.

Then the Dashboard works fine.
Tested to comment out the line and restart. Same error came back. Removed comment and restarted and then it worked again.
So I'm pretty sure the "indices.query.bool.max_clause_count: 2000" line is fixing it.

**Comment by t3chn0m4g3** [comment]
@Patrik-Hansson Thanks for taking the time to test this. Before I put this setting in the elasticsearch image can you check if large data sets take any longer to load, i.e. loading each honeypot dashboard with data for as long as you have data available.

**Comment by Patrik-Hansson** [comment]
Will reboot my vm and do some timed dashboard loads.
Is there some commands or views that can show my amount of data. So you know how much i have ?
I can of course see the number of attacks and how many days, but maybe you know of some better way to get statistics/amount of data ?

**Comment by Patrik-Hansson** [comment]
T-pot dashboard going from 15 minutes to 90 days: 22 seconds. (I only have from 8 january i noticed)
Changed to a day, 9 seconds. Changed to 30 days, 10 seconds.

No idea i these are good values or not, but i don't notice a difference from what it was before.
cowrie is largest dataset with 1.7 millions attacks.

**Comment by t3chn0m4g3** [comment]
Thank you!

**Comment by t3chn0m4g3** [comment]
With T-Pot 20.06 I cleaned up the index pattern down to about 700. This increases things drastically. If you are upgrading from a previous version you will find the index pattern as part of the export in `tpot/etc/export/kibana_export.ndjson.zip`. Just unzip and import via Kibana.
